### ISSUE TITLE
how to use it in chrome

### ISSUE THREAD

**Issue by mattxzhang** [onlylemi/download-any-for-github#2]
hi,I just download the code,but don't know how to add it to chrome

**Comment by dalu9527** [comment]
please tell us how to use in readme

**Comment by onlylemi** [comment]
hey @mattxzhang, @dalu9527 

I add the method of install  in `README` and you can use it. And if you any questions, please tell me. Thank you.

**Comment by mattxzhang** [comment]
hi @onlylemi method 2 works,thanks

**Comment by onlylemi** [comment]
hey @mattxzhang ,

ok, that' good. Please tell me if you other questions in use. Thank you.

**Comment by meritozh** [comment]
@onlylemi Chrome will disable it because this extension doesn't exist in Chrome Web Store. Will you publish it later?

**Comment by onlylemi** [comment]
hey @meritozh ,

u can try method 2,  it's good. At present I don't publish it and will do it later.
