### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by lolstudio** [onlylemi/download-any-for-github#3]
doesn't work,please fix it.

**Comment by onlylemi** [comment]
hey @lolstudio ,

u can look here. https://github.com/onlylemi/download-any-for-github#install. And many people also can use it and work well. Please try it again. If you any question, please tell me.

**Comment by lolstudio** [comment]
hey @onlylemi 
best , it's work, my environment is win,chrome version 51, yesterday i installed this plugin  .but doesn't work. environment is mac,chrome version 51, i will try again tonight and give feedback, thx .

**Comment by lolstudio** [comment]
hey @onlylemi 
i try again , it's work, OMG, thx

**Comment by onlylemi** [comment]
hey @lolstudio ,

ok, that's good.
