### ISSUE TITLE
把包拖进扩展，过段时间还是退出或失效

### ISSUE THREAD

**Issue by willisworley** [onlylemi/download-any-for-github#4]
应该是 chrome 扩展认证机制的问题，能否上架 chrome 商店呢？

**Comment by onlylemi** [comment]
hi @zddewe 

确实有这个问题，之后会考虑上架到 chrome 商店的

**Comment by onlylemi** [comment]
@zddewe 进行了打包 可以尝试下载 README 中 `github-downloader-extension.crx` 文件然后拖到扩展里
